import { useState } from 'react'
import { IconHeartHandshake, IconRadar, IconSend, IconShieldCheck, IconUserPlus } from '@tabler/icons-react'
import { useAppStore } from '../store/useAppStore'

export default function MatePage(){
 const {pair,matching,startMatching,cancelMatching,sendNudge}=useAppStore(); const [prefs,setPrefs]=useState(matching.preferences)
 if(pair) return <div className="mate-page-v16"><header className="section-title"><p className="eyebrow">DIARY MATE</p><h1>서로의 우주를 알아가는 중</h1></header><section className="mate-profile-card"><div className="mate-avatar">✦</div><div><span>{pair.mode==='anonymous'?'익명으로 연결된 Mate':'친구와 연결됨'}</span><h2>{pair.mate?.nickname||'연결 대기 중'}</h2><p>{pair.pairStreak}일째 함께 기록하고 있어요.</p></div><button className="ghost-button" onClick={sendNudge}><IconSend size={17}/> 별빛 신호</button></section><section className="relationship-steps"><h2>우리의 Orbit</h2>{['First Signal','Orbit','Starlight','Connection'].map((s,i)=><div key={s} className={s===pair.stage?'active':''}><span>{i+1}</span><strong>{s}</strong><small>{i===0?'가벼운 취향과 일상을 나눠요':i===1?'조금 더 깊은 생각을 발견해요':i===2?'추억과 사진이 별자리가 돼요':'서로 동의하면 더 많은 기능이 열려요'}</small></div>)}</section><section className="safety-card"><IconShieldCheck/><div><h3>연결은 언제나 양쪽의 동의로</h3><p>개인정보 공개, 자유 메시지, 오프라인 참여는 모두 서로 동의해야 열려요.</p></div></section></div>
 return <div className="mate-page-v16"><header className="section-title"><p className="eyebrow">FIND YOUR ORBIT</p><h1>누구와 첫 질문을 나눌까요?</h1><p>친구를 초대하거나, 아직 모르는 누군가의 별빛 신호를 찾아보세요.</p></header><section className="match-options"><article><IconUserPlus/><h2>아는 사람과 시작</h2><p>페어 코드를 보내 둘만의 우주를 만들어요.</p><button className="secondary-action">페어 코드 만들기</button></article><article><IconRadar/><h2>새로운 Mate 만나기</h2><p>프로필 사진보다 매일의 답변으로 서로를 알아가요.</p><select value={prefs.genderPreference} onChange={e=>setPrefs({...prefs,genderPreference:e.target.value})}><option value="any">성별 상관없음</option><option value="female">여성과 연결</option><option value="male">남성과 연결</option></select><select value={prefs.vibe} onChange={e=>setPrefs({...prefs,vibe:e.target.value})}><option>English habit friend</option><option>편하게 이야기할 친구</option><option>새로운 사람 알아가기</option><option>친구 또는 연애 가능성 모두 열어두기</option></select>{matching.status==='searching'?<button className="ghost-button" onClick={cancelMatching}>매칭 취소</button>:<button className="primary-action" onClick={()=>startMatching(prefs)}><IconHeartHandshake size={18}/> 별빛 신호 찾기</button>}</article></section>{matching.status==='searching'&&<div className="matching-radar"><div/><h2>당신과 비슷한 시간에 쓰는 Mate를 찾는 중...</h2><p>외모가 아니라 관심사와 기록 습관을 먼저 맞추고 있어요.</p></div>}</div>
}
