import { IconBrush, IconLock, IconSparkles, IconStars } from '@tabler/icons-react'
import { starterPairLooks } from '../data/pairContent'
import { useAppStore } from '../store/useAppStore'

export default function OurUniversePage(){
 const {pair,user,updatePairStyle}=useAppStore()
 if(!pair)return <div className="empty-orbit-page"><div className="empty-planet">🌌</div><h1>아직 둘만의 우주가 없어요.</h1><p>Diary Mate와 연결되면 두 Comet 사이에 첫 별빛이 생겨요.</p></div>
 return <div className="universe-v16"><div className="space-dust"/><header className="universe-hud"><div><span>OUR UNIVERSE</span><h1>{user.nickname} & {pair.mate?.nickname||'Mate'}</h1></div><div className="universe-score"><IconSparkles size={17}/>{pair.pairLight} Pair Light</div></header><section className="shared-orbit"><div className="orbit-ring r1"/><div className="orbit-ring r2"/><div className="shared-planet"><div className="planet-glow"/><span>🪐</span><small>Day {pair.pairStreak}</small></div><div className="universe-comet left"><b>☄</b><span>{user.cometName}</span><i>{starterPairLooks.find(x=>x.id===pair.sharedStyle)?.left}</i></div><div className="universe-comet right"><b>✦</b><span>{pair.mate?.cometName||'Mate'}</span><i>{starterPairLooks.find(x=>x.id===pair.sharedStyle)?.right}</i></div>{Array.from({length:Math.min(16,pair.constellationStars)},(_,i)=><span key={i} className="constellation-star" style={{'--x':`${12+(i*37)%76}%`,'--y':`${18+(i*29)%64}%`}}>✦</span>)}</section><section className="universe-controls"><article><IconStars/><div><span>공동 별자리</span><strong>{pair.constellationStars}개의 별</strong></div></article><article><IconLock/><div><span>다음 해금</span><strong>{pair.pairStreak<14?`${14-pair.pairStreak}일 뒤 공동 행성 성장`:'새 장식 해금 가능'}</strong></div></article></section><section className="pair-style-panel"><div><IconBrush/><h2>Pair Look</h2><p>두 캐릭터가 함께 있을 때 완성되는 스타일이에요.</p></div><div className="pair-look-grid">{starterPairLooks.map(style=><button key={style.id} className={pair.sharedStyle===style.id?'active':''} onClick={()=>updatePairStyle(style.id)}><span>{style.left} + {style.right}</span><strong>{style.name}</strong></button>)}</div></section></div>
}
