import { useState } from 'react'
import { IconCamera, IconCheck, IconLock, IconSend, IconSparkles } from '@tabler/icons-react'
import { dailyQuestions, quickReactions } from '../data/pairContent'
import { useAppStore } from '../store/useAppStore'

export default function PairDiaryPage(){
 const {todayEntry,setMyAnswer,setMyPhoto,submitMyEntry,simulateMateEntry,addReaction,saveTodayMemory,pair}=useAppStore(); const [showFeedback,setShowFeedback]=useState(false); const q=dailyQuestions.find(x=>x.id===todayEntry.questionId)||dailyQuestions[0]
 const upload=e=>{const file=e.target.files?.[0]; if(file){const reader=new FileReader(); reader.onload=()=>setMyPhoto(reader.result); reader.readAsDataURL(file)}}
 return <div className="diary-v16">
  <header className="section-title"><p className="eyebrow">TODAY'S SIGNAL · {q.category}</p><h1>{q.question}</h1><p>{q.ko}</p></header>
  {!todayEntry.mySubmitted?<section className="writing-sheet-v16"><div className="starter-chip">문장이 막히면 이렇게 시작해보세요<br/><strong>{q.starter}</strong></div><textarea value={todayEntry.myAnswer} onChange={e=>setMyAnswer(e.target.value)} placeholder="완벽한 영어보다, 오늘의 진짜 이야기를 남겨보세요."/><div className="writing-footer"><label className="photo-upload"><IconCamera size={18}/>{todayEntry.myPhoto?'사진 바꾸기':'오늘의 순간 첨부'}<input type="file" accept="image/*" onChange={upload}/></label><span>{todayEntry.myAnswer.trim().split(/\s+/).filter(Boolean).length} words</span></div>{todayEntry.myPhoto&&<img className="diary-photo-preview" src={todayEntry.myPhoto} alt="오늘의 순간"/>}{q.photoPrompt&&<p className="photo-hint">{q.photoHint}</p>}<button className="primary-wide" onClick={submitMyEntry}><IconSend size={18}/> 내 별빛 보내기</button></section>:
   <section className="waiting-sheet"><div className="waiting-stars"><span className="done">✦</span><i/><span className={todayEntry.mateSubmitted?'done':'waiting'}>✦</span></div><h2>{todayEntry.unlocked?'오늘의 이야기가 열렸어요':'상대의 별빛을 기다리는 중'}</h2><p>{todayEntry.unlocked?'두 사람이 모두 답했어요. 이제 서로의 이야기를 천천히 읽어보세요.':'내 답변은 안전하게 저장되었어요. Mate가 작성하면 동시에 공개돼요.'}</p>{!todayEntry.mateSubmitted&&<button className="ghost-button" onClick={simulateMateEntry}>테스트: Mate 답변 도착시키기</button>}</section>}
  {todayEntry.unlocked&&<><section className="unlocked-grid"><article className="answer-card mine"><span className="answer-label">MY STORY</span><h3>나의 답변</h3><p>{todayEntry.myAnswer}</p>{todayEntry.myPhoto&&<img src={todayEntry.myPhoto} alt="내 사진"/>}</article><article className="answer-card mate"><span className="answer-label">{pair?.mate?.nickname||'MATE'}'S STORY</span><h3>상대의 답변</h3><p>{todayEntry.mateAnswer}</p></article></section><section className="reaction-panel"><h3>이 답변을 읽고 어떤 마음이 들었나요?</h3><div>{quickReactions.map(r=><button key={r.id} onClick={()=>addReaction(r)}><span>{r.emoji}</span>{r.label}</button>)}</div></section><section className="feedback-drawer"><button onClick={()=>setShowFeedback(v=>!v)}><IconSparkles size={18}/>{showFeedback?'영어 도움 닫기':'내 영어도 살펴보기'}</button>{showFeedback&&<div className="feedback-content"><p><span>더 자연스럽게</span>{todayEntry.feedback?.natural}</p><p><span>오늘 가져갈 표현</span><strong>{todayEntry.feedback?.expression}</strong></p><small>{todayEntry.feedback?.meaning}</small></div>}</section><button className="memory-save" onClick={saveTodayMemory}><IconCheck size={18}/> 오늘을 별빛 보관함에 저장</button></>}
  {!todayEntry.unlocked&&todayEntry.mySubmitted&&<div className="locked-next"><IconLock/><span>다음 공동 질문은 두 사람의 답변이 모두 도착하면 열려요.</span></div>}
 </div>
}
